#ifndef AUDIORECORDER_WINDOWS_GLOBAL_H
#define AUDIORECORDER_WINDOWS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AUDIORECORDER_WINDOWS_LIBRARY)
#define AUDIORECORDER_WINDOWS_EXPORT Q_DECL_EXPORT
#else
#define AUDIORECORDER_WINDOWS_EXPORT Q_DECL_IMPORT
#endif

#endif // AUDIORECORDER_WINDOWS_GLOBAL_H
